firstname=input("enter your firstname")
print(firstname)
lastname=input("enter your lastname")
print(lastname)
age=input("enter your age")
print(age)
ssno=input("enter your ssno")
print(ssno)
Height=input("enter your height")
print(Height)
Weight=input("enter your Weight")
print(Weight)